source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!
target ‘ChedliWeldi2’ do
    pod 'Alamofire', '~> 4.0'
    pod 'UIFloatLabelTextField'
    pod 'SkyFloatingLabelTextField', '~> 3.0'
    pod 'DatePickerDialog'
    pod 'SwiftyJSON'
    pod 'Kingfisher', '~> 3.13.1'
    pod 'SimulatorRemoteNotifications'
    pod 'FoldingCell'
    pod 'PopupDialog', '~> 0.5.4'
    pod 'Cosmos', git: 'https://github.com/marketplacer/Cosmos.git', tag: '8.0.2'
    pod 'INSPhotoGallery'
    pod 'XLPagerTabStrip', :git => 'https://github.com/KelvinJin/XLPagerTabStrip', :branch => 'swift3'
    pod 'TagListView', '~> 1.2.0'
    pod 'FSCalendar'
    pod 'NMessenger'
    pod 'EasyNotificationBadge'
    pod 'INSNibLoading'
    pod 'RAMAnimatedTabBarController'
    pod 'YALSideMenu', '~> 2.0'
    pod 'TransitionButton'
    pod 'FoldingTabBar', '~> 1.1'
end
